# Generated by Django 4.1.6 on 2023-02-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emai_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='works_full_time',
            field=models.BooleanField(default=True),
        ),
    ]
