# Generated by Django 4.1.6 on 2023-02-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_level',
            field=models.CharField(default='Junior', max_length=20),
        ),
    ]
