# Generated by Django 4.1.6 on 2023-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_job_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='month_of_employment',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'Aril'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=3),
            preserve_default=False,
        ),
    ]
