# Generated by Django 4.1.6 on 2023-02-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
