# Generated by Django 4.2.1 on 2023-05-30 11:04

import custom_validators.custom_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=250, validators=[custom_validators.custom_validators.validate_comma_separated], verbose_name='Ingredients'),
        ),
    ]
