# Generated by Django 4.2.1 on 2023-05-26 09:12

import Custom_validators.custom_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(15), Custom_validators.custom_validators.isalnum_and_underscore], verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
            ],
        ),
    ]
